/**
 * @module auraTheme
 * @description Theme definition for "aura".
 */

import type { ThemeDefinition } from "../types";

export const auraTheme: ThemeDefinition = {
  name: "aura",
  label: "Aura",
  radius: "1rem",
  light: {
    background: "#fdfcfd",
    foreground: "#15141b",
    card: "#f9f8ff",
    cardForeground: "#15141b",
    popover: "#ffffff",
    popoverForeground: "#15141b",
    primary: "#9d7cd8",
    primaryForeground: "#ffffff",
    secondary: "#f0ebff",
    secondaryForeground: "#583da1",
    muted: "#f4f2ff",
    mutedForeground: "#7e76a3",
    accent: "#eeeaff",
    accentForeground: "#583da1",
    destructive: "#ff5a5f",
    destructiveForeground: "#ffffff",
    border: "#e8e4ff",
    input: "#e8e4ff",
    ring: "#9d7cd8",
    chart1: "#9d7cd8",
    chart2: "#7dc4e4",
    chart3: "#7cd8a7",
    chart4: "#d87ca0",
    chart5: "#d8b97c",
    sidebar: "#f9f8ff",
    sidebarForeground: "#15141b",
    sidebarPrimary: "#9d7cd8",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#eeeaff",
    sidebarAccentForeground: "#583da1",
    sidebarBorder: "#e8e4ff",
    sidebarRing: "#9d7cd8",
    navbar: "#15141b",
    navbarForeground: "#f9f8ff",
    inputBackground: "#ffffff",
    tableHeader: "#f4f2ff",
    tableHeaderForeground: "#7e76a3",
    tableRowHover: "#f9f8ff",
    tableRowSelected: "#eeeaff",
    dialog: "#ffffff",
    dialogForeground: "#15141b",
    sheet: "#ffffff",
    sheetForeground: "#15141b",
    command: "#ffffff",
    commandForeground: "#15141b",
    dropdown: "#ffffff",
    dropdownForeground: "#15141b",
  },
  dark: {
    background: "#15141b",
    foreground: "#edecee",
    card: "#1b1a23",
    cardForeground: "#edecee",
    popover: "#15141b",
    popoverForeground: "#edecee",
    primary: "#9d7cd8",
    primaryForeground: "#15141b",
    secondary: "#252334",
    secondaryForeground: "#edecee",
    muted: "#252334",
    mutedForeground: "#948eaf",
    accent: "#2d2b45",
    accentForeground: "#edecee",
    destructive: "#ff5a5f",
    destructiveForeground: "#ffffff",
    border: "#2d2b45",
    input: "#2d2b45",
    ring: "#9d7cd8",
    chart1: "#9d7cd8",
    chart2: "#7dc4e4",
    chart3: "#7cd8a7",
    chart4: "#d87ca0",
    chart5: "#d8b97c",
    sidebar: "#15141b",
    sidebarForeground: "#948eaf",
    sidebarPrimary: "#9d7cd8",
    sidebarPrimaryForeground: "#15141b",
    sidebarAccent: "#252334",
    sidebarAccentForeground: "#edecee",
    sidebarBorder: "#2d2b45",
    sidebarRing: "#9d7cd8",
    navbar: "#0d0c12",
    navbarForeground: "#edecee",
    inputBackground: "#15141b",
    tableHeader: "#1b1a23",
    tableHeaderForeground: "#948eaf",
    tableRowHover: "#1b1a23",
    tableRowSelected: "#2d2b45",
    dialog: "#1b1a23",
    dialogForeground: "#edecee",
    sheet: "#1b1a23",
    sheetForeground: "#edecee",
    command: "#1b1a23",
    commandForeground: "#edecee",
    dropdown: "#1b1a23",
    dropdownForeground: "#edecee",
  },
};
