/**
 * @module botanistTheme
 * @description Theme definition for "botanist".
 */

import type { ThemeDefinition } from "../types";

export const botanistTheme: ThemeDefinition = {
  name: "botanist",
  label: "Botanist",
  radius: "0.5rem",
  light: {
    background: "#f9fbf7",
    foreground: "#1a1d1a",
    card: "#ffffff",
    cardForeground: "#1a1d1a",
    popover: "#ffffff",
    popoverForeground: "#1a1d1a",
    primary: "#6b8e23",
    primaryForeground: "#ffffff",
    secondary: "#f0f4ef",
    secondaryForeground: "#3a4d39",
    muted: "#f0f4ef",
    mutedForeground: "#6b7c6b",
    accent: "#e4ece4",
    accentForeground: "#3a4d39",
    destructive: "#bc4749",
    destructiveForeground: "#ffffff",
    border: "#e4ece4",
    input: "#ffffff",
    ring: "#6b8e23",
    chart1: "#6b8e23",
    chart2: "#3a4d39",
    chart3: "#a9af7e",
    chart4: "#e2e4c0",
    chart5: "#1a1d1a",
    sidebar: "#f0f4ef",
    sidebarForeground: "#1a1d1a",
    sidebarPrimary: "#6b8e23",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#e4ece4",
    sidebarAccentForeground: "#3a4d39",
    sidebarBorder: "#dae2da",
    sidebarRing: "#6b8e23",
    navbar: "#3a4d39",
    navbarForeground: "#f9fbf7",
    inputBackground: "#ffffff",
    tableHeader: "#f0f4ef",
    tableHeaderForeground: "#6b7c6b",
    tableRowHover: "#f9fbf7",
    tableRowSelected: "#e4ece4",
    dialog: "#ffffff",
    dialogForeground: "#1a1d1a",
    sheet: "#ffffff",
    sheetForeground: "#1a1d1a",
    command: "#ffffff",
    commandForeground: "#1a1d1a",
    dropdown: "#ffffff",
    dropdownForeground: "#1a1d1a",
  },
  dark: {
    background: "#1a1d1a",
    foreground: "#e4ece4",
    card: "#242924",
    cardForeground: "#e4ece4",
    popover: "#1a1d1a",
    popoverForeground: "#e4ece4",
    primary: "#8eb33b",
    primaryForeground: "#1a1d1a",
    secondary: "#242924",
    secondaryForeground: "#e4ece4",
    muted: "#242924",
    mutedForeground: "#8fa38f",
    accent: "#323a32",
    accentForeground: "#e4ece4",
    destructive: "#bc4749",
    destructiveForeground: "#ffffff",
    border: "#323a32",
    input: "#242924",
    ring: "#8eb33b",
    chart1: "#8eb33b",
    chart2: "#6b8e23",
    chart3: "#a9af7e",
    chart4: "#8fa38f",
    chart5: "#e4ece4",
    sidebar: "#121412",
    sidebarForeground: "#8fa38f",
    sidebarPrimary: "#8eb33b",
    sidebarPrimaryForeground: "#1a1d1a",
    sidebarAccent: "#242924",
    sidebarAccentForeground: "#e4ece4",
    sidebarBorder: "#323a32",
    sidebarRing: "#8eb33b",
    navbar: "#121412",
    navbarForeground: "#8eb33b",
    inputBackground: "#1a1d1a",
    tableHeader: "#242924",
    tableHeaderForeground: "#8fa38f",
    tableRowHover: "#242924",
    tableRowSelected: "#323a32",
    dialog: "#242924",
    dialogForeground: "#e4ece4",
    sheet: "#242924",
    sheetForeground: "#e4ece4",
    command: "#242924",
    commandForeground: "#e4ece4",
    dropdown: "#242924",
    dropdownForeground: "#e4ece4",
  },
};
