/**
 * @module glacierTheme
 * @description Theme definition for "glacier".
 */

import type { ThemeDefinition } from "../types";

export const glacierTheme: ThemeDefinition = {
  name: "glacier",
  label: "Glacier",
  radius: "0.375rem",
  light: {
    background: "#fcfdfe",
    foreground: "#0b1117",
    card: "#ffffff",
    cardForeground: "#0b1117",
    popover: "#ffffff",
    popoverForeground: "#0b1117",
    primary: "#00d2ff",
    primaryForeground: "#ffffff",
    secondary: "#e6f9ff",
    secondaryForeground: "#007a99",
    muted: "#f0fafd",
    mutedForeground: "#668c99",
    accent: "#ccf2ff",
    accentForeground: "#007a99",
    destructive: "#ff4d4d",
    destructiveForeground: "#ffffff",
    border: "#e6f2f7",
    input: "#ffffff",
    ring: "#00d2ff",
    chart1: "#00d2ff",
    chart2: "#3a7bd5",
    chart3: "#007a99",
    chart4: "#668c99",
    chart5: "#0b1117",
    sidebar: "#f0fafd",
    sidebarForeground: "#0b1117",
    sidebarPrimary: "#00d2ff",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#ccf2ff",
    sidebarAccentForeground: "#007a99",
    sidebarBorder: "#dae9f0",
    sidebarRing: "#00d2ff",
    navbar: "#0b1117",
    navbarForeground: "#ffffff",
    inputBackground: "#ffffff",
    tableHeader: "#f0fafd",
    tableHeaderForeground: "#668c99",
    tableRowHover: "#fcfdfe",
    tableRowSelected: "#ccf2ff",
    dialog: "#ffffff",
    dialogForeground: "#0b1117",
    sheet: "#ffffff",
    sheetForeground: "#0b1117",
    command: "#ffffff",
    commandForeground: "#0b1117",
    dropdown: "#ffffff",
    dropdownForeground: "#0b1117",
  },
  dark: {
    background: "#0b1117",
    foreground: "#e6f9ff",
    card: "#121d26",
    cardForeground: "#e6f9ff",
    popover: "#0b1117",
    popoverForeground: "#e6f9ff",
    primary: "#00d2ff",
    primaryForeground: "#0b1117",
    secondary: "#1a2b36",
    secondaryForeground: "#e6f9ff",
    muted: "#1a2b36",
    mutedForeground: "#8bb3cc",
    accent: "#223d4d",
    accentForeground: "#e6f9ff",
    destructive: "#b33030",
    destructiveForeground: "#ffffff",
    border: "#223d4d",
    input: "#1a2b36",
    ring: "#00d2ff",
    chart1: "#00d2ff",
    chart2: "#3a7bd5",
    chart3: "#007a99",
    chart4: "#8bb3cc",
    chart5: "#e6f9ff",
    sidebar: "#070c10",
    sidebarForeground: "#8bb3cc",
    sidebarPrimary: "#00d2ff",
    sidebarPrimaryForeground: "#0b1117",
    sidebarAccent: "#1a2b36",
    sidebarAccentForeground: "#e6f9ff",
    sidebarBorder: "#223d4d",
    sidebarRing: "#00d2ff",
    navbar: "#070c10",
    navbarForeground: "#00d2ff",
    inputBackground: "#0b1117",
    tableHeader: "#1a2b36",
    tableHeaderForeground: "#8bb3cc",
    tableRowHover: "#1a2b36",
    tableRowSelected: "#223d4d",
    dialog: "#121d26",
    dialogForeground: "#e6f9ff",
    sheet: "#121d26",
    sheetForeground: "#e6f9ff",
    command: "#121d26",
    commandForeground: "#e6f9ff",
    dropdown: "#121d26",
    dropdownForeground: "#e6f9ff",
  },
};
