/**
 * @module nebulaTheme
 * @description Theme definition for "nebula".
 */

import type { ThemeDefinition } from "../types";

export const nebulaTheme: ThemeDefinition = {
  name: "nebula",
  label: "Nebula",
  radius: "0.75rem",
  light: {
    background: "#fdfaff",
    foreground: "#0d0221",
    card: "#ffffff",
    cardForeground: "#0d0221",
    popover: "#ffffff",
    popoverForeground: "#0d0221",
    primary: "#bc13fe",
    primaryForeground: "#ffffff",
    secondary: "#f0e6ff",
    secondaryForeground: "#240046",
    muted: "#f0e6ff",
    mutedForeground: "#7b2cbf",
    accent: "#e0ccff",
    accentForeground: "#240046",
    destructive: "#ff0054",
    destructiveForeground: "#ffffff",
    border: "#e0ccff",
    input: "#ffffff",
    ring: "#bc13fe",
    chart1: "#bc13fe",
    chart2: "#7b2cbf",
    chart3: "#3c096c",
    chart4: "#5a189a",
    chart5: "#0d0221",
    sidebar: "#f0e6ff",
    sidebarForeground: "#0d0221",
    sidebarPrimary: "#bc13fe",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#e0ccff",
    sidebarAccentForeground: "#240046",
    sidebarBorder: "#d0b3ff",
    sidebarRing: "#bc13fe",
    navbar: "#240046",
    navbarForeground: "#fdfaff",
    inputBackground: "#ffffff",
    tableHeader: "#f0e6ff",
    tableHeaderForeground: "#7b2cbf",
    tableRowHover: "#fdfaff",
    tableRowSelected: "#e0ccff",
    dialog: "#ffffff",
    dialogForeground: "#0d0221",
    sheet: "#ffffff",
    sheetForeground: "#0d0221",
    command: "#ffffff",
    commandForeground: "#0d0221",
    dropdown: "#ffffff",
    dropdownForeground: "#0d0221",
  },
  dark: {
    background: "#0d0221",
    foreground: "#e0ccff",
    card: "#150833",
    cardForeground: "#e0ccff",
    popover: "#0d0221",
    popoverForeground: "#e0ccff",
    primary: "#bc13fe",
    primaryForeground: "#0d0221",
    secondary: "#240046",
    secondaryForeground: "#e0ccff",
    muted: "#240046",
    mutedForeground: "#9d4edd",
    accent: "#3c096c",
    accentForeground: "#ffffff",
    destructive: "#ff0054",
    destructiveForeground: "#ffffff",
    border: "#3c096c",
    input: "#150833",
    ring: "#bc13fe",
    chart1: "#bc13fe",
    chart2: "#9d4edd",
    chart3: "#7b2cbf",
    chart4: "#5a189a",
    chart5: "#e0ccff",
    sidebar: "#050114",
    sidebarForeground: "#9d4edd",
    sidebarPrimary: "#bc13fe",
    sidebarPrimaryForeground: "#0d0221",
    sidebarAccent: "#240046",
    sidebarAccentForeground: "#e0ccff",
    sidebarBorder: "#3c096c",
    sidebarRing: "#bc13fe",
    navbar: "#050114",
    navbarForeground: "#bc13fe",
    inputBackground: "#0d0221",
    tableHeader: "#240046",
    tableHeaderForeground: "#9d4edd",
    tableRowHover: "#240046",
    tableRowSelected: "#3c096c",
    dialog: "#150833",
    dialogForeground: "#e0ccff",
    sheet: "#150833",
    sheetForeground: "#e0ccff",
    command: "#150833",
    commandForeground: "#e0ccff",
    dropdown: "#150833",
    dropdownForeground: "#e0ccff",
  },
};
