/**
 * @module outlookTheme
 * @description Theme definition for "outlook".
 */

import type { ThemeDefinition } from "../types";

export const outlookTheme: ThemeDefinition = {
  name: "outlook",
  label: "Outlook",
  radius: "0.5rem",
  light: {
    background: "#f3f2f1",
    foreground: "#323130",
    card: "#ffffff",
    cardForeground: "#323130",
    popover: "#ffffff",
    popoverForeground: "#323130",
    primary: "#0078d4",
    primaryForeground: "#ffffff",
    secondary: "#ffffff",
    secondaryForeground: "#0078d4",
    muted: "#f3f2f1",
    mutedForeground: "#605e5c",
    accent: "#edebe9",
    accentForeground: "#323130",
    destructive: "#d13438",
    destructiveForeground: "#ffffff",
    border: "#e1dfdd",
    input: "#ffffff",
    ring: "#0078d4",
    chart1: "#0078d4",
    chart2: "#004578",
    chart3: "#106ebe",
    chart4: "#50e6ff",
    chart5: "#005a9e",
    sidebar: "#f0f0f0",
    sidebarForeground: "#323130",
    sidebarPrimary: "#0078d4",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#e1dfdd",
    sidebarAccentForeground: "#000000",
    sidebarBorder: "#e1dfdd",
    sidebarRing: "#0078d4",
    navbar: "#0078d4",
    navbarForeground: "#ffffff",
    inputBackground: "#ffffff",
    tableHeader: "#ffffff",
    tableHeaderForeground: "#605e5c",
    tableRowHover: "#f3f2f1",
    tableRowSelected: "#edebe9",
    dialog: "#ffffff",
    dialogForeground: "#323130",
    sheet: "#ffffff",
    sheetForeground: "#323130",
    command: "#ffffff",
    commandForeground: "#323130",
    dropdown: "#ffffff",
    dropdownForeground: "#323130",
  },
  dark: {
    background: "#201f1e",
    foreground: "#ffffff",
    card: "#2d2d2d",
    cardForeground: "#ffffff",
    popover: "#2d2d2d",
    popoverForeground: "#ffffff",
    primary: "#2899f5",
    primaryForeground: "#ffffff",
    secondary: "#3b3a39",
    secondaryForeground: "#ffffff",
    muted: "#3b3a39",
    mutedForeground: "#a19f9d",
    accent: "#3b3a39",
    accentForeground: "#ffffff",
    destructive: "#d13438",
    destructiveForeground: "#ffffff",
    border: "#3b3a39",
    input: "#3b3a39",
    ring: "#2899f5",
    chart1: "#2899f5",
    chart2: "#004578",
    chart3: "#106ebe",
    chart4: "#50e6ff",
    chart5: "#005a9e",
    sidebar: "#252423",
    sidebarForeground: "#ffffff",
    sidebarPrimary: "#2899f5",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#3b3a39",
    sidebarAccentForeground: "#ffffff",
    sidebarBorder: "#3b3a39",
    sidebarRing: "#2899f5",
    navbar: "#005a9e",
    navbarForeground: "#ffffff",
    inputBackground: "#2d2d2d",
    tableHeader: "#2d2d2d",
    tableHeaderForeground: "#a19f9d",
    tableRowHover: "#3b3a39",
    tableRowSelected: "#444444",
    dialog: "#2d2d2d",
    dialogForeground: "#ffffff",
    sheet: "#2d2d2d",
    sheetForeground: "#ffffff",
    command: "#2d2d2d",
    commandForeground: "#ffffff",
    dropdown: "#2d2d2d",
    dropdownForeground: "#ffffff",
  },
};
