/**
 * @module rubyTheme
 * @description Theme definition for "ruby".
 */

import type { ThemeDefinition } from "../types";

export const rubyTheme: ThemeDefinition = {
  name: "ruby",
  label: "Ruby",
  radius: "0.5rem",
  light: {
    background: "#ffffff",
    foreground: "#450a0a",
    card: "#fef2f2",
    cardForeground: "#450a0a",
    popover: "#ffffff",
    popoverForeground: "#450a0a",
    primary: "#991b1b",
    primaryForeground: "#ffffff",
    secondary: "#fee2e2",
    secondaryForeground: "#7f1d1d",
    muted: "#fef2f2",
    mutedForeground: "#b91c1c",
    accent: "#fee2e2",
    accentForeground: "#7f1d1d",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
    border: "#fee2e2",
    input: "#fee2e2",
    ring: "#991b1b",
    chart1: "#991b1b",
    chart2: "#b91c1c",
    chart3: "#dc2626",
    chart4: "#ef4444",
    chart5: "#f87171",
    sidebar: "#fef2f2",
    sidebarForeground: "#450a0a",
    sidebarPrimary: "#991b1b",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#fee2e2",
    sidebarAccentForeground: "#7f1d1d",
    sidebarBorder: "#fecaca",
    sidebarRing: "#991b1b",
    navbar: "#450a0a",
    navbarForeground: "#ffffff",
    inputBackground: "#ffffff",
    tableHeader: "#fee2e2",
    tableHeaderForeground: "#b91c1c",
    tableRowHover: "#fee2e2",
    tableRowSelected: "#fecaca",
    dialog: "#ffffff",
    dialogForeground: "#450a0a",
    sheet: "#ffffff",
    sheetForeground: "#450a0a",
    command: "#ffffff",
    commandForeground: "#450a0a",
    dropdown: "#ffffff",
    dropdownForeground: "#450a0a",
  },
  dark: {
    background: "#450a0a",
    foreground: "#fee2e2",
    card: "#7f1d1d",
    cardForeground: "#fee2e2",
    popover: "#450a0a",
    popoverForeground: "#fee2e2",
    primary: "#f87171",
    primaryForeground: "#450a0a",
    secondary: "#7f1d1d",
    secondaryForeground: "#fee2e2",
    muted: "#7f1d1d",
    mutedForeground: "#fca5a5",
    accent: "#991b1b",
    accentForeground: "#fee2e2",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
    border: "#991b1b",
    input: "#991b1b",
    ring: "#f87171",
    chart1: "#f87171",
    chart2: "#ef4444",
    chart3: "#dc2626",
    chart4: "#b91c1c",
    chart5: "#991b1b",
    sidebar: "#450a0a",
    sidebarForeground: "#fee2e2",
    sidebarPrimary: "#f87171",
    sidebarPrimaryForeground: "#450a0a",
    sidebarAccent: "#7f1d1d",
    sidebarAccentForeground: "#fee2e2",
    sidebarBorder: "#991b1b",
    sidebarRing: "#f87171",
    navbar: "#2d0a0a",
    navbarForeground: "#fee2e2",
    inputBackground: "#450a0a",
    tableHeader: "#7f1d1d",
    tableHeaderForeground: "#fca5a5",
    tableRowHover: "#7f1d1d",
    tableRowSelected: "#991b1b",
    dialog: "#7f1d1d",
    dialogForeground: "#fee2e2",
    sheet: "#7f1d1d",
    sheetForeground: "#fee2e2",
    command: "#7f1d1d",
    commandForeground: "#fee2e2",
    dropdown: "#7f1d1d",
    dropdownForeground: "#fee2e2",
  },
};
