/**
 * @module vanguardTheme
 * @description Theme definition for "vanguard".
 */

import type { ThemeDefinition } from "../types";

export const vanguardTheme: ThemeDefinition = {
  name: "vanguard",
  label: "Vanguard",
  radius: "0rem",
  light: {
    background: "#ffffff",
    foreground: "#1a1a1a",
    card: "#f2f2f2",
    cardForeground: "#1a1a1a",
    popover: "#ffffff",
    popoverForeground: "#1a1a1a",
    primary: "#ff5f1f",
    primaryForeground: "#ffffff",
    secondary: "#1a1a1a",
    secondaryForeground: "#ffffff",
    muted: "#f2f2f2",
    mutedForeground: "#666666",
    accent: "#ff5f1f",
    accentForeground: "#ffffff",
    destructive: "#d00000",
    destructiveForeground: "#ffffff",
    border: "#dddddd",
    input: "#ffffff",
    ring: "#ff5f1f",
    chart1: "#ff5f1f",
    chart2: "#1a1a1a",
    chart3: "#666666",
    chart4: "#999999",
    chart5: "#cccccc",
    sidebar: "#1a1a1a",
    sidebarForeground: "#ffffff",
    sidebarPrimary: "#ff5f1f",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#333333",
    sidebarAccentForeground: "#ffffff",
    sidebarBorder: "#333333",
    sidebarRing: "#ff5f1f",
    navbar: "#1a1a1a",
    navbarForeground: "#ffffff",
    inputBackground: "#ffffff",
    tableHeader: "#f2f2f2",
    tableHeaderForeground: "#1a1a1a",
    tableRowHover: "#f9f9f9",
    tableRowSelected: "#ff5f1f22",
    dialog: "#ffffff",
    dialogForeground: "#1a1a1a",
    sheet: "#ffffff",
    sheetForeground: "#1a1a1a",
    command: "#ffffff",
    commandForeground: "#1a1a1a",
    dropdown: "#ffffff",
    dropdownForeground: "#1a1a1a",
  },
  dark: {
    background: "#0a0a0a",
    foreground: "#ffffff",
    card: "#141414",
    cardForeground: "#ffffff",
    popover: "#0a0a0a",
    popoverForeground: "#ffffff",
    primary: "#ff5f1f",
    primaryForeground: "#ffffff",
    secondary: "#ffffff",
    secondaryForeground: "#0a0a0a",
    muted: "#1a1a1a",
    mutedForeground: "#888888",
    accent: "#ff5f1f",
    accentForeground: "#ffffff",
    destructive: "#ff3333",
    destructiveForeground: "#ffffff",
    border: "#262626",
    input: "#141414",
    ring: "#ff5f1f",
    chart1: "#ff5f1f",
    chart2: "#ffffff",
    chart3: "#888888",
    chart4: "#444444",
    chart5: "#262626",
    sidebar: "#000000",
    sidebarForeground: "#ffffff",
    sidebarPrimary: "#ff5f1f",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#1a1a1a",
    sidebarAccentForeground: "#ffffff",
    sidebarBorder: "#262626",
    sidebarRing: "#ff5f1f",
    navbar: "#000000",
    navbarForeground: "#ff5f1f",
    inputBackground: "#0a0a0a",
    tableHeader: "#1a1a1a",
    tableHeaderForeground: "#888888",
    tableRowHover: "#141414",
    tableRowSelected: "#ff5f1f33",
    dialog: "#141414",
    dialogForeground: "#ffffff",
    sheet: "#141414",
    sheetForeground: "#ffffff",
    command: "#141414",
    commandForeground: "#ffffff",
    dropdown: "#141414",
    dropdownForeground: "#ffffff",
  },
};
