/**
 * @module violetTheme
 * @description Theme definition for "violet".
 */

import type { ThemeDefinition } from "../types";

export const violetTheme: ThemeDefinition = {
  name: "violet",
  label: "Violet",
  radius: "0.5rem",
  light: {
    background: "#ffffff",
    foreground: "#2e1065",
    card: "#f5f3ff",
    cardForeground: "#2e1065",
    popover: "#ffffff",
    popoverForeground: "#2e1065",
    primary: "#7c3aed",
    primaryForeground: "#ffffff",
    secondary: "#ede9fe",
    secondaryForeground: "#4c1d95",
    muted: "#f5f3ff",
    mutedForeground: "#6d28d9",
    accent: "#ede9fe",
    accentForeground: "#4c1d95",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#ede9fe",
    input: "#ede9fe",
    ring: "#7c3aed",
    chart1: "#7c3aed",
    chart2: "#8b5cf6",
    chart3: "#a78bfa",
    chart4: "#c4b5fd",
    chart5: "#ddd6fe",
    sidebar: "#f5f3ff",
    sidebarForeground: "#2e1065",
    sidebarPrimary: "#7c3aed",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#ede9fe",
    sidebarAccentForeground: "#4c1d95",
    sidebarBorder: "#ddd6fe",
    sidebarRing: "#7c3aed",
    navbar: "#2e1065",
    navbarForeground: "#ffffff",
    inputBackground: "#ffffff",
    tableHeader: "#ede9fe",
    tableHeaderForeground: "#6d28d9",
    tableRowHover: "#ede9fe",
    tableRowSelected: "#ddd6fe",
    dialog: "#ffffff",
    dialogForeground: "#2e1065",
    sheet: "#ffffff",
    sheetForeground: "#2e1065",
    command: "#ffffff",
    commandForeground: "#2e1065",
    dropdown: "#ffffff",
    dropdownForeground: "#2e1065",
  },
  dark: {
    background: "#2e1065",
    foreground: "#f5f3ff",
    card: "#4c1d95",
    cardForeground: "#f5f3ff",
    popover: "#2e1065",
    popoverForeground: "#f5f3ff",
    primary: "#a78bfa",
    primaryForeground: "#2e1065",
    secondary: "#4c1d95",
    secondaryForeground: "#f5f3ff",
    muted: "#4c1d95",
    mutedForeground: "#c4b5fd",
    accent: "#5b21b6",
    accentForeground: "#f5f3ff",
    destructive: "#991b1b",
    destructiveForeground: "#f5f3ff",
    border: "#5b21b6",
    input: "#5b21b6",
    ring: "#a78bfa",
    chart1: "#a78bfa",
    chart2: "#8b5cf6",
    chart3: "#7c3aed",
    chart4: "#6d28d9",
    chart5: "#5b21b6",
    sidebar: "#2e1065",
    sidebarForeground: "#f5f3ff",
    sidebarPrimary: "#a78bfa",
    sidebarPrimaryForeground: "#2e1065",
    sidebarAccent: "#4c1d95",
    sidebarAccentForeground: "#f5f3ff",
    sidebarBorder: "#5b21b6",
    sidebarRing: "#a78bfa",
    navbar: "#1e0a45",
    navbarForeground: "#f5f3ff",
    inputBackground: "#2e1065",
    tableHeader: "#4c1d95",
    tableHeaderForeground: "#c4b5fd",
    tableRowHover: "#4c1d95",
    tableRowSelected: "#5b21b6",
    dialog: "#4c1d95",
    dialogForeground: "#f5f3ff",
    sheet: "#4c1d95",
    sheetForeground: "#f5f3ff",
    command: "#4c1d95",
    commandForeground: "#f5f3ff",
    dropdown: "#4c1d95",
    dropdownForeground: "#f5f3ff",
  },
};
