/**
 * @module youtubeTheme
 * @description Theme definition for "youtube".
 */

import type { ThemeDefinition } from "../types";

export const youtubeTheme: ThemeDefinition = {
  name: "youtube",
  label: "YouTube",
  radius: "0.25rem",
  light: {
    background: "#ffffff",
    foreground: "#0f0f0f",
    card: "#f2f2f2",
    cardForeground: "#0f0f0f",
    popover: "#ffffff",
    popoverForeground: "#0f0f0f",
    primary: "#ff0000",
    primaryForeground: "#ffffff",
    secondary: "#f2f2f2",
    secondaryForeground: "#0f0f0f",
    muted: "#f2f2f2",
    mutedForeground: "#606060",
    accent: "#e5e5e5",
    accentForeground: "#0f0f0f",
    destructive: "#cc0000",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
    ring: "#ff0000",
    chart1: "#ff0000",
    chart2: "#065fd4",
    chart3: "#107516",
    chart4: "#606060",
    chart5: "#0f0f0f",
    sidebar: "#ffffff",
    sidebarForeground: "#0f0f0f",
    sidebarPrimary: "#ff0000",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#f2f2f2",
    sidebarAccentForeground: "#0f0f0f",
    sidebarBorder: "#e5e5e5",
    sidebarRing: "#ff0000",
    navbar: "#ffffff",
    navbarForeground: "#0f0f0f",
    inputBackground: "#ffffff",
    tableHeader: "#f2f2f2",
    tableHeaderForeground: "#606060",
    tableRowHover: "#f2f2f2",
    tableRowSelected: "#e5e5e5",
    dialog: "#ffffff",
    dialogForeground: "#0f0f0f",
    sheet: "#ffffff",
    sheetForeground: "#0f0f0f",
    command: "#ffffff",
    commandForeground: "#0f0f0f",
    dropdown: "#ffffff",
    dropdownForeground: "#0f0f0f",
  },
  dark: {
    background: "#0f0f0f",
    foreground: "#f1f1f1",
    card: "#272727",
    cardForeground: "#f1f1f1",
    popover: "#0f0f0f",
    popoverForeground: "#f1f1f1",
    primary: "#ff0000",
    primaryForeground: "#ffffff",
    secondary: "#272727",
    secondaryForeground: "#f1f1f1",
    muted: "#272727",
    mutedForeground: "#aaaaaa",
    accent: "#3f3f3f",
    accentForeground: "#f1f1f1",
    destructive: "#cc0000",
    destructiveForeground: "#ffffff",
    border: "#3f3f3f",
    input: "#3f3f3f",
    ring: "#ff0000",
    chart1: "#ff0000",
    chart2: "#3ea6ff",
    chart3: "#2ba640",
    chart4: "#aaaaaa",
    chart5: "#f1f1f1",
    sidebar: "#0f0f0f",
    sidebarForeground: "#f1f1f1",
    sidebarPrimary: "#ff0000",
    sidebarPrimaryForeground: "#ffffff",
    sidebarAccent: "#272727",
    sidebarAccentForeground: "#f1f1f1",
    sidebarBorder: "#3f3f3f",
    sidebarRing: "#ff0000",
    navbar: "#0f0f0f",
    navbarForeground: "#f1f1f1",
    inputBackground: "#0f0f0f",
    tableHeader: "#272727",
    tableHeaderForeground: "#aaaaaa",
    tableRowHover: "#272727",
    tableRowSelected: "#3f3f3f",
    dialog: "#0f0f0f",
    dialogForeground: "#f1f1f1",
    sheet: "#0f0f0f",
    sheetForeground: "#f1f1f1",
    command: "#0f0f0f",
    commandForeground: "#f1f1f1",
    dropdown: "#0f0f0f",
    dropdownForeground: "#f1f1f1",
  },
};
