import type { JSX } from "react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { gql, useMutation } from "@apollo/client";
import { BookOpen, RefreshCcw, Save } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/lib/components/ui/button";
import { Input } from "@/lib/components/ui/input";
import { Textarea } from "@/lib/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/lib/components/ui/card";
import { Separator } from "@/lib/components/ui/separator";
import { ModelAdvancedFiltersControl, type FilterSeedSpec } from "@/lib/table/components/filtering";
import type { ComplexFilterInput } from "@/lib/table/compat/types";
import {
  build_create_mutation,
  type CreateMutationResponse,
  type CreateMutationVariables,
} from "@/lib/form/mutations";

/**
 * Props for the reporting dataset creation panel.
 * @property onCreated - Callback invoked after successful creation.
 * @property title - Optional panel title.
 * @property description - Optional helper text.
 */
export type ReportingDatasetPanelProps = {
  onCreated?: (datasetId: string) => void;
  title?: string;
  description?: string;
  /** Selected source app label (when controlled by the parent). */
  sourceAppLabel?: string;
  /** Selected source model name (when controlled by the parent). */
  sourceModel?: string;
  /** When true, hides the Source app/model input fields. */
  hideSourceInputs?: boolean;
};

/**
 * GraphQL object selection returned by dataset create mutation.
 * @property id - Dataset identifier.
 * @property code - Dataset code.
 * @property title - Dataset title.
 */
export type ReportingDatasetCreateObject = {
  id: string;
  code: string;
  title: string;
};

/**
 * GraphQL response for the dataset create mutation.
 * @property response - Standard create mutation payload.
 */
export type ReportingDatasetCreateResponse = {
  response: CreateMutationResponse<ReportingDatasetCreateObject>;
};

/**
 * Dataset creation input typed as `Record<string, unknown>` for flexible JSON fields.
 *
 * The backend expects JSON scalars for: `dimensions`, `metrics`, `computed_fields`,
 * `default_filters`, `ordering`, `metadata`.
 */
export type ReportingDatasetCreateInput = Record<string, unknown>;

/**
 * Default filter spec stored in `ReportingDataset.default_filters`.
 *
 * The backend normalizes this list into Django `Q` objects when executing BI datasets.
 */
export type ReportingDatasetDefaultFilterSpec = FilterSeedSpec & {
  /** When true, the generated predicate is negated. */
  negate?: boolean;
};

const CREATE_DATASET_MUTATION = gql(
  build_create_mutation("ReportingDataset", "id code title"),
);

/**
 * Narrow type guard for plain objects.
 *
 * @param value - Unknown value.
 * @returns True when `value` is a non-null object and not an array.
 */
function isPlainObject(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

/**
 * Convert a `ComplexFilterInput` payload into the list-based BI `default_filters` format.
 *
 * Notes:
 * - The BI backend accepts a flat list of filter specs with `connector` ("and"/"or") and `negate`.
 * - The advanced filter builder supports nested groups; this helper flattens groups while
 *   preserving a best-effort connector/negation for each leaf predicate.
 *
 * @param payload - Advanced filter payload generated by the UI.
 * @returns List of filter specs suitable for `ReportingDataset.default_filters`.
 */
function payloadToDefaultFilterSpecs(
  payload: ComplexFilterInput<string> | null,
): ReportingDatasetDefaultFilterSpec[] {
  if (!payload) return [];

  const walk = (
    node: ComplexFilterInput<string>,
    connector: "and" | "or",
    negate: boolean,
  ): ReportingDatasetDefaultFilterSpec[] => {
    const specs: ReportingDatasetDefaultFilterSpec[] = [];

    const andParts = (node.AND ?? []) as Array<ComplexFilterInput<string>>;
    andParts.forEach((part) => {
      specs.push(...walk(part, "and", negate));
    });

    const orParts = (node.OR ?? []) as Array<ComplexFilterInput<string>>;
    orParts.forEach((part) => {
      specs.push(...walk(part, "or", negate));
    });

    if (node.NOT && isPlainObject(node.NOT)) {
      specs.push(
        ...walk(node.NOT as ComplexFilterInput<string>, connector, true),
      );
    }

    Object.entries(node).forEach(([key, value]) => {
      if (key === "AND" || key === "OR" || key === "NOT") return;
      if (value === undefined) return;

      const keyParts = key.split("__");
      const maybeLookup =
        keyParts.length > 1 ? keyParts[keyParts.length - 1] : null;
      const fieldFromKey =
        maybeLookup && maybeLookup.length > 0
          ? keyParts.slice(0, -1).join("__")
          : key;

      if (isPlainObject(value)) {
        Object.entries(value).forEach(([lookup, inner]) => {
          specs.push({
            field: fieldFromKey,
            lookup,
            value: inner,
            connector,
            negate,
          });
        });
        return;
      }

      specs.push({
        field: fieldFromKey,
        lookup: maybeLookup ?? "exact",
        value,
        connector,
        negate,
      });
    });

    return specs;
  };

  return walk(payload, "and", false);
}

/**
 * Safe JSON parser for editor fields.
 *
 * @param value - JSON string.
 * @param fallback - Fallback value returned when parsing fails.
 * @returns Parsed value when valid, otherwise fallback.
 */
function parseJsonField<T>(value: string, fallback: T): T {
  try {
    const parsed = JSON.parse(value || "null");
    return (parsed ?? fallback) as T;
  } catch {
    return fallback;
  }
}

/**
 * Reporting dataset creation panel.
 */
export function ReportingDatasetPanel({
  onCreated,
  sourceAppLabel,
  sourceModel,
  hideSourceInputs = false,
  title = "CrÃ©er un dataset BI",
  description = "DÃ©finissez la source (modÃ¨le Django) puis les dimensions/mesures. Le dataset devient exÃ©cutable via GraphQL (preview/run_query).",
}: ReportingDatasetPanelProps): JSX.Element {
  const [draft, setDraft] = useState(() => ({
    code: "dataset-custom",
    title: "Nouveau dataset",
    description: "",
    source_app_label: sourceAppLabel ?? "assets",
    source_model: sourceModel ?? "Equipment",
    source_kind: "model",
    preview_limit: 50,
    ordering: '["-id"]',
    default_filters: "[]",
    dimensions:
      '[\n  { "name": "id", "field": "id", "label": "ID" }\n]',
    metrics:
      '[\n  { "name": "count", "field": "pk", "aggregation": "count", "label": "Count" }\n]',
    computed_fields: "[]",
    metadata:
      '{\n  "quick_fields": ["id"],\n  "cache_ttl_seconds": 0,\n  "max_limit": 5000,\n  "allow_ad_hoc": false\n}',
  }));

  /**
   * Keep the internal draft source in sync when the page controls app/model selection.
   */
  useEffect(() => {
    if (!sourceAppLabel && !sourceModel) return;
    setDraft((prev) => {
      const next = {
        ...prev,
        source_app_label: sourceAppLabel ?? prev.source_app_label,
        source_model: sourceModel ?? prev.source_model,
      };
      if (
        next.source_app_label === prev.source_app_label &&
        next.source_model === prev.source_model
      ) {
        return prev;
      }
      return next;
    });
  }, [sourceAppLabel, sourceModel]);

  const [createDataset, { loading: creating }] = useMutation<
    ReportingDatasetCreateResponse,
    CreateMutationVariables<ReportingDatasetCreateInput>
  >(CREATE_DATASET_MUTATION);

  /**
   * Validate JSON fields and return an assembled mutation input.
   *
   * @returns Mutation input object or null when validation fails.
   */
  const buildInput = useCallback((): ReportingDatasetCreateInput | null => {
    const ordering = parseJsonField<Array<string>>(draft.ordering, []);
    const defaultFilters = parseJsonField<Array<ReportingDatasetDefaultFilterSpec>>(
      draft.default_filters,
      [],
    );
    const dimensions = parseJsonField<Array<Record<string, unknown>>>(draft.dimensions, []);
    const metrics = parseJsonField<Array<Record<string, unknown>>>(draft.metrics, []);
    const computedFields = parseJsonField<Array<Record<string, unknown>>>(draft.computed_fields, []);
    const metadata = parseJsonField<Record<string, unknown>>(draft.metadata, {});

    const invalidJson =
      ordering === null ||
      defaultFilters === null ||
      dimensions === null ||
      metrics === null ||
      computedFields === null ||
      metadata === null;

    if (invalidJson) {
      toast.error("JSON invalide dans un champ (ordering/filters/dimensions/metrics/metadata).");
      return null;
    }

    if (!draft.code.trim() || !draft.title.trim()) {
      toast.error("Code et titre sont requis.");
      return null;
    }
    if (!draft.source_app_label.trim() || !draft.source_model.trim()) {
      toast.error("Source app/model est requis.");
      return null;
    }

    return {
      code: draft.code.trim(),
      title: draft.title.trim(),
      description: draft.description ?? "",
      source_app_label: draft.source_app_label.trim(),
      source_model: draft.source_model.trim(),
      source_kind: draft.source_kind,
      preview_limit: Number(draft.preview_limit || 50),
      ordering,
      default_filters: defaultFilters,
      dimensions,
      metrics,
      computed_fields: computedFields,
      metadata,
    };
  }, [draft]);

  /**
   * Execute dataset creation.
   */
  const handleCreate = useCallback(async () => {
    const input = buildInput();
    if (!input) return;
    const { data } = await createDataset({ variables: { input } });
    if (data?.response?.ok && data.response.object?.id) {
      toast.success("Dataset BI crÃ©Ã©.");
      onCreated?.(data.response.object.id);
      return;
    }
    toast.error(
      data?.response?.errors?.map((e) => e?.message).join(", ") || "CrÃ©ation impossible.",
    );
  }, [buildInput, createDataset, onCreated]);

  /**
   * A small â€œcheatsheetâ€ example to help first-time users.
   */
  const cheatsheet = useMemo(
    () => (
      <div className="space-y-2 text-xs text-muted-foreground">
        <p className="flex items-center gap-2">
          <BookOpen className="h-4 w-4" /> Exemples rapides:
        </p>
        <ul className="list-disc space-y-1 pl-5">
          <li>
            Time-series: dimension transform <code>trunc:month</code> sur <code>created_at</code>
          </li>
          <li>
            Mesure conditionnelle: ajoutez <code>filter</code> dans une mÃ©trique (count filtrÃ©)
          </li>
          <li>
            Limites/caching: configurez <code>metadata.max_limit</code> et <code>metadata.cache_ttl_seconds</code>
          </li>
        </ul>
      </div>
    ),
    [],
  );

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader className="space-y-2">
          <CardTitle className="text-base">{title}</CardTitle>
          <CardDescription>{description}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-3 lg:grid-cols-3">
            <div className="space-y-2">
              <label className="text-xs font-semibold text-muted-foreground">Code</label>
              <Input
                value={draft.code}
                onChange={(e) => setDraft((p) => ({ ...p, code: e.target.value }))}
              />
            </div>
            <div className="space-y-2">
              <label className="text-xs font-semibold text-muted-foreground">Titre</label>
              <Input
                value={draft.title}
                onChange={(e) => setDraft((p) => ({ ...p, title: e.target.value }))}
              />
            </div>
            <div className="space-y-2">
              <label className="text-xs font-semibold text-muted-foreground">Preview limit</label>
              <Input
                type="number"
                min={1}
                value={draft.preview_limit}
                onChange={(e) => setDraft((p) => ({ ...p, preview_limit: Number(e.target.value || 0) }))}
              />
            </div>
          </div>

          <div className="space-y-2">
            <label className="text-xs font-semibold text-muted-foreground">Description</label>
            <Textarea
              rows={3}
              value={draft.description}
              onChange={(e) => setDraft((p) => ({ ...p, description: e.target.value }))}
            />
          </div>

          <Separator />

          {hideSourceInputs ? (
            <div className="grid gap-3 lg:grid-cols-3">
              <div className="space-y-1">
                <p className="text-xs font-semibold text-muted-foreground">Source app label</p>
                <p className="text-sm font-medium">{draft.source_app_label}</p>
              </div>
              <div className="space-y-1">
                <p className="text-xs font-semibold text-muted-foreground">Source model</p>
                <p className="text-sm font-medium">{draft.source_model}</p>
              </div>
              <div className="space-y-1">
                <p className="text-xs font-semibold text-muted-foreground">Source kind</p>
                <p className="text-sm font-medium">{draft.source_kind}</p>
              </div>
            </div>
          ) : (
            <div className="grid gap-3 lg:grid-cols-3">
              <div className="space-y-2">
                <label className="text-xs font-semibold text-muted-foreground">Source app label</label>
                <Input
                  value={draft.source_app_label}
                  onChange={(e) => setDraft((p) => ({ ...p, source_app_label: e.target.value }))}
                  placeholder="inventory"
                />
              </div>
              <div className="space-y-2">
                <label className="text-xs font-semibold text-muted-foreground">Source model</label>
                <Input
                  value={draft.source_model}
                  onChange={(e) => setDraft((p) => ({ ...p, source_model: e.target.value }))}
                  placeholder="PartConsumption"
                />
              </div>
              <div className="space-y-2">
                <label className="text-xs font-semibold text-muted-foreground">Source kind</label>
                <select
                  className="w-full rounded-md border bg-background p-2 text-sm"
                  value={draft.source_kind}
                  onChange={(e) => setDraft((p) => ({ ...p, source_kind: e.target.value }))}
                >
                  <option value="model">Django model</option>
                  <option value="sql">SQL (reserved)</option>
                  <option value="graphql">GraphQL (reserved)</option>
                  <option value="python">Python (reserved)</option>
                </select>
              </div>
            </div>
          )}

          <Separator />

          <div className="grid gap-3 lg:grid-cols-2">
            <div className="space-y-2">
              <label className="text-xs font-semibold text-muted-foreground">Dimensions (JSON)</label>
              <Textarea
                className="min-h-[220px] font-mono text-xs"
                value={draft.dimensions}
                onChange={(e) => setDraft((p) => ({ ...p, dimensions: e.target.value }))}
              />
            </div>
            <div className="space-y-2">
              <label className="text-xs font-semibold text-muted-foreground">Metrics (JSON)</label>
              <Textarea
                className="min-h-[220px] font-mono text-xs"
                value={draft.metrics}
                onChange={(e) => setDraft((p) => ({ ...p, metrics: e.target.value }))}
              />
            </div>
          </div>

          <div className="grid gap-3 lg:grid-cols-2">
            <div className="space-y-2">
              <label className="text-xs font-semibold text-muted-foreground">Computed fields (JSON)</label>
              <Textarea
                className="min-h-[160px] font-mono text-xs"
                value={draft.computed_fields}
                onChange={(e) => setDraft((p) => ({ ...p, computed_fields: e.target.value }))}
              />
              <p className="text-[11px] text-muted-foreground">
                Exemple: <code>{"{ \"name\": \"avg_cost\", \"formula\": \"total_cost / count\", \"stage\": \"query\" }"}</code>
              </p>
            </div>
            <div className="space-y-2">
              <label className="text-xs font-semibold text-muted-foreground">Metadata (JSON)</label>
              <Textarea
                className="min-h-[160px] font-mono text-xs"
                value={draft.metadata}
                onChange={(e) => setDraft((p) => ({ ...p, metadata: e.target.value }))}
              />
              {cheatsheet}
            </div>
          </div>

          <div className="grid gap-3 lg:grid-cols-2">
            <div className="space-y-2">
              <div className="flex items-center justify-between gap-2">
                <label className="text-xs font-semibold text-muted-foreground">
                  Default filters (JSON)
                </label>
                <ModelAdvancedFiltersControl
                  appName={draft.source_app_label.trim() || "assets"}
                  modelName={draft.source_model.trim() || "Equipment"}
                  displayMode="dialog"
                  buttonLabel="Composer"
                  buttonSize="sm"
                  buttonVariant="outline"
                  showChips={false}
                  popupTitle="Composer les filtres par dÃ©faut"
                  dialogSizing={{ width: "90vw", maxWidth: 900, maxHeight: "80vh" }}
                  seedSpecs={parseJsonField<Array<FilterSeedSpec>>(draft.default_filters, [])}
                  onApply={(filters) => {
                    const specs = payloadToDefaultFilterSpecs(filters);
                    setDraft((p) => ({
                      ...p,
                      default_filters: JSON.stringify(specs, null, 2),
                    }));
                    toast.success("Filtres par dÃ©faut mis Ã  jour depuis le builder.");
                  }}
                />
              </div>
              <Textarea
                className="min-h-[120px] font-mono text-xs"
                value={draft.default_filters}
                onChange={(e) => setDraft((p) => ({ ...p, default_filters: e.target.value }))}
              />
            </div>
            <div className="space-y-2">
              <label className="text-xs font-semibold text-muted-foreground">Ordering (JSON)</label>
              <Textarea
                className="min-h-[120px] font-mono text-xs"
                value={draft.ordering}
                onChange={(e) => setDraft((p) => ({ ...p, ordering: e.target.value }))}
              />
            </div>
          </div>

          <div className="flex flex-wrap items-center justify-end gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => {
                setDraft((p) => ({ ...p }));
                toast.message("Conseil: exÃ©cutez ensuite un preview/run_query depuis la table ou le studio.");
              }}
            >
              <RefreshCcw className="mr-2 h-4 w-4" />
              Astuce
            </Button>
            <Button
              variant="default"
              size="sm"
              onClick={() => void handleCreate()}
              disabled={creating}
            >
              <Save className="mr-2 h-4 w-4" />
              {creating ? "CrÃ©ation..." : "CrÃ©er le dataset"}
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

