export const ROUTES = {
  AFFECTATION_HISTORIQUE_LIST: "/operations/affectation-historique",
  AFFECTATION_HISTORIQUE_CREATE: "/operations/affectation-historique/create",
  AFFECTATION_HISTORIQUE_EDIT: "/operations/affectation-historique/:id/edit",
  AFFECTATION_HISTORIQUE_DETAIL: "/operations/affectation-historique/:id",
  DECHARGE_LIST: "/operations/decharge",
  DECHARGE_CREATE: "/operations/decharge/create",
  DECHARGE_EDIT: "/operations/decharge/:id/edit",
  DECHARGE_DETAIL: "/operations/decharge/:id",
  RESTITUTION_LIST: "/operations/restitution",
  RESTITUTION_CREATE: "/operations/restitution/create",
  RESTITUTION_EDIT: "/operations/restitution/:id/edit",
  RESTITUTION_DETAIL: "/operations/restitution/:id",
  BENEFICIAIRE_LIST: "/operations/beneficiaire",
  BENEFICIAIRE_CREATE: "/operations/beneficiaire/create",
  BENEFICIAIRE_EDIT: "/operations/beneficiaire/:id/edit",
  BENEFICIAIRE_DETAIL: "/operations/beneficiaire/:id",
} as const;
