export const ROUTES = {
  DECHARGE_LIST: "/operations/decharge",
  DECHARGE_CREATE: "/operations/decharge/create",
  DECHARGE_EDIT: "/operations/decharge/:id/edit",
  DECHARGE_DETAIL: "/operations/decharge/:id",
  RESTITUTION_LIST: "/operations/restitution",
  RESTITUTION_CREATE: "/operations/restitution/create",
  RESTITUTION_EDIT: "/operations/restitution/:id/edit",
  RESTITUTION_DETAIL: "/operations/restitution/:id",
  BENEFICIAIRE_LIST: "/operations/beneficiaire",
  BENEFICIAIRE_CREATE: "/operations/beneficiaire/create",
  BENEFICIAIRE_EDIT: "/operations/beneficiaire/:id/edit",
  BENEFICIAIRE_DETAIL: "/operations/beneficiaire/:id",
  DECHARGE_LIGNE_LIST: "/operations/decharge-ligne",
  DECHARGE_LIGNE_CREATE: "/operations/decharge-ligne/create",
  DECHARGE_LIGNE_EDIT: "/operations/decharge-ligne/:id/edit",
  DECHARGE_LIGNE_DETAIL: "/operations/decharge-ligne/:id",
  RESTITUTION_LIGNE_LIST: "/operations/restitution-ligne",
} as const;
