// AI-GENERATED: Review required
// Generated by: Assistant
// Purpose: Provide full GraphQL query and strict TypeScript types for model_form_metadata.
// Notes:
// - Includes all variables: app_name, model_name, nested_fields
// - Includes all fields for ModelFormMetadataType, FormFieldMetadataType, and FormRelationshipMetadataType
// - Fixed union variants for Django field types and relationship types
// - No external dependencies (gql) required; the query is a plain string constant

/* eslint-disable max-len */

/**

- Purpose: Strict JSON value type
  */
export type json_value =
  | string
  | number
  | boolean
  | null
  | { [key: string]: json_value }
  | json_value[];
/**

- Purpose: Fixed union for Django field types as returned by field_type
- Note: Includes common Django core fields; extend if your project uses additional custom fields.
  */
export type django_field_type =
  | "AutoField"
  | "BigAutoField"
  | "SmallAutoField"
  | "IntegerField"
  | "BigIntegerField"
  | "SmallIntegerField"
  | "PositiveIntegerField"
  | "PositiveSmallIntegerField"
  | "FloatField"
  | "DecimalField"
  | "BooleanField"
  | "NullBooleanField"
  | "CharField"
  | "TextField"
  | "EmailField"
  | "URLField"
  | "SlugField"
  | "UUIDField"
  | "BinaryField"
  | "FileField"
  | "ImageField"
  | "DateField"
  | "DateTimeField"
  | "TimeField"
  | "DurationField"
  | "JSONField"
  | "GenericIPAddressField"
  | "ForeignKey"
  | "OneToOneField"
  | "ManyToManyField";
/**

- Purpose: Fixed union for relationship_type
- Note: relationship metadata also provides booleans for foreign_key, many_to_many, one_to_one;
- if your backend returns additional relationship types, extend this union accordingly.
  */
export type relationship_type =
  | "ForeignKey"
  | "OneToOneField"
  | "ManyToManyField"
  | "ReverseForeignKey"
  | "ReverseOneToOne"
  | "ReverseManyToMany"
  | "ManyToOneRel";
/**

- Purpose: ChoiceType mapping (value/label pairs)
  */
export interface choice {
  value: string;
  label: string;
}
export interface field_permission_metadata {
  can_read: boolean;
  can_write: boolean;
  visibility: "visible" | "hidden" | "masked" | "redacted";
  access_level: string;
  mask_value?: string | null;
  reason?: string | null;
}

export interface model_permission_matrix {
  can_create: boolean;
  can_update: boolean;
  can_delete: boolean;
  can_read: boolean;
  can_list: boolean;
  can_history: boolean;
  reasons?: Record<string, string | null> | null;
}

/**

- Purpose: FormFieldMetadataType mapping
- Mirrors GraphQL fields and uses strict types; JSON-like fields are typed as json_value.
  */
export interface form_field_metadata {
  name: string;
  field_type: django_field_type;
  is_required: boolean;
  verbose_name: string;
  help_text?: string;
  widget_type:
    | "textarea"
    | "email"
    | "url"
    | "checkbox"
    | "datetime-local"
    | "date"
    | "number"
    | "select"
    | "multiselect"
    | "text";
  placeholder?: string;
  default_value?: json_value;
  choices?: choice[];
  max_length?: number;
  min_length?: number;
  decimal_places?: number;
  max_digits?: number;
  min_value?: number;
  max_value?: number;
  auto_now: boolean;
  auto_now_add: boolean;
  blank: boolean;
  null: boolean;
  unique: boolean;
  editable: boolean;
  validators?: string[];
  error_messages?: { [key: string]: string } | null;
  disabled: boolean;
  readonly: boolean;
  css_classes?: string;
  data_attributes?: { [key: string]: json_value } | null;
  has_permission: boolean;
  permissions?: field_permission_metadata | null;
}
/**

- Purpose: FormRelationshipMetadataType mapping
  */
export interface form_relationship_metadata {
  name: string;
  relationship_type: relationship_type;
  verbose_name: string;
  help_text?: string;
  widget_type: string;
  is_required: boolean;

  related_model: string;
  related_app: string;
  to_field?: string | null;
  from_field: string;

  many_to_many: boolean;
  one_to_one: boolean;
  foreign_key: boolean;
  is_reverse: boolean;

  multiple: boolean;
  queryset_filters?: json_value;
  empty_label?: string | null;
  limit_choices_to?: json_value;

  disabled: boolean;
  readonly: boolean;
  css_classes?: string;
  data_attributes?: { [key: string]: json_value } | null;
  has_permission: boolean;
  permissions?: field_permission_metadata | null;
}
/**

- Purpose: ModelFormMetadataType mapping
- Note: nested is a one-level deep recursion per backend description; it reuses this interface.
  */
export interface model_form_metadata {
  /** Stable metadata version used for caching */
  metadataVersion: string;
  app_name: string;
  model_name: string;
  verbose_name: string;
  verbose_name_plural: string;
  form_title: string;
  form_description?: string | null;
  fields: form_field_metadata[];
  relationships: form_relationship_metadata[];
  /**
   * name = graphene.String(description="Deprecated: use field_name; retained for compatibility")
  field_name = graphene.String(description="Parent relationship field name that produced this nested metadata")
  relationship_type = graphene.String(description="Relationship type for the parent field (ForeignKey, ManyToManyField, OneToOneField)")
  to_field = graphene.String(description="Target field name on the related model (if specified)")
  from_field = graphene.String(description="Source field name on the parent model")
  is_required = graphene.Boolean(description="Whether the parent relationship field is required")
   */
  name?: string;
  field_name?: string;
  relationship_type?: relationship_type;
  to_field?: string | null;
  from_field?: string | null;
  is_required?: boolean;

  nested: model_form_metadata[]; // depth 1 per the backend resolver

  field_order?: string[] | null;
  exclude_fields: string[];
  readonly_fields: string[];

  required_permissions: string[];
  form_validation_rules?: json_value;

  form_layout?: json_value;
  css_classes?: string | null;
  form_attributes?: json_value;
  permissions?: model_permission_matrix | null;
}
/**

- Purpose: Query variables for model_form_metadata
  */
export interface model_form_metadata_variables {
  /** Django app label */
  app_name: string;
  /** Django model class name */
  model_name: string;
  /** List of field names to include nested metadata for (depth 1) */
  nested_fields: string[];
  /** List of field names to exclude */
  exclude?: string[];
  /** List of field names to include */
  only?: string[];
  /** List of relationship names to exclude */
  exclude_relationships?: string[];
  /** List of relationship names to include */
  only_relationships?: string[];
}
/**

- Purpose: Full GraphQL result type for model_form_metadata query
  */
export interface model_form_metadata_query_result {
  model_form_metadata: model_form_metadata | null;
}
/**

- Purpose: Helper to build query variables in snake_case
- Args:
- app_name: Django app label
- model_name: Django model class name
- nested_fields: List of field names to include nested metadata for (depth 1)
- Returns:
- model_form_metadata_variables
- Example:
- const vars = build_model_form_metadata_variables("core", "Article", ["author"]);
  */
export function build_model_form_metadata_variables(
  app_name: string,
  model_name: string,
  nested_fields: string[] = []
): model_form_metadata_variables {
  return {
    app_name,
    model_name,
    nested_fields,
  };
}
